apiVersion: apps/v1
kind: Deployment
metadata:
    name: dev-ops
    labels:
        app: dev-ops
spec:
    replicas: {{ .Values.replicas }}
    selector:
        matchLabels:
            app: dev-ops
    template:
        metadata:
            labels:
                app: dev-ops
        spec:
          containers:
          - name: devops
            image: {{ .Values.repo }}
            ports:
            - containerPort: 8020
---
apiVersion: v1
kind: Service
metadata:
    name: dev-ops
spec:
    type: NodePort
    selector:
        app: dev-ops
    ports:
        - name: port8080
          protocol: TCP
          nodePort: {{ .Values.nodeport}}
          port: 8080
          targetPort: 8080
